name: 'Terraform-Development'

on:
  push:
    branches:
    - main
    paths-ignore:
      - '**/README.md'
  pull_request:

permissions:
  contents: read

jobs:
  development:
    name: 'Development'
    uses: ./.github/workflows/terraform-template.yml
    with:
      environment: "dev"
      resourceGroup: "rg-terraform-dev"
      team: "DevOps"
      region: "uksouth"
    secrets:
      apiToken: "${{ secrets.TF_API_TOKEN }}"
      gitHubToken: "${{ secrets.GITHUB_TOKEN }}"