name: 'Terraform-Development'

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

env:
  environment: "dev"
  resourceGroup: "rg-terraform-dev"
  team: "DevOps"
  region: "uksouth"
  
jobs:
  development:
    name: 'Development'
    uses: ./.github/workflows/terraform-template.yml
    with:
      environment: $environment
      resourceGroup: $resourceGroup
      team: $team
      region: $region
    secrets:
      apiToken: "${{ secrets.TF_API_TOKEN }}"
      gitHubToken: "${{ secrets.GITHUB_TOKEN }}"
